hwi_oauth:
    firewall_names: [main]
    resource_owners:
        facebook:
            type: facebook
            client_id: "%facebook.app.id%"
            client_secret: "%facebook.app.secret%"
            scope : "email,public_profile,manage_pages"
            infos_url: "https://graph.facebook.com/me?fields=id,name,email,picture.type(large)"